# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gram_schimdtCpp <- function(A) {
    .Call('_fpta_gram_schimdtCpp', PACKAGE = 'fpta', A)
}

Schur_wrapperCpp <- function(projection) {
    .Call('_fpta_Schur_wrapperCpp', PACKAGE = 'fpta', projection)
}

predictCpp <- function(B1, B2, Coef) {
    .Call('_fpta_predictCpp', PACKAGE = 'fpta', B1, B2, Coef)
}

