#' @useDynLib fpta
#' @import Rcpp
#' @import RcppArmadillo
#'
NULL
#' Calculate the projection matrix based on Hilbert projection theorem
#'
#' @param B n x k matrix, with B_ij represented by ith data point evaluated using j th basis function
#' @param f_val n x n  matrix, with i,j th entry representing f(x_i, x_j)
#' @param GramMatrix the matrix generated by Gram-Schmit process
#'
#' @return a k x k projection matrix
update_projection = function(B, f_val, GramMatrix){
  k = dim(B)[2]
  n = dim(B)[1]
  #for odd number of basis functions, pad the projection with 0
  if(k %% 2 == 1){
    projection = matrix(0, nrow = k+1, ncol = k+1)
  }else{
    projection = matrix(0, nrow = k, ncol = k)
  }
  temp = B %*% GramMatrix
  projection[1:k,1:k] = 1/n^2 *crossprod(temp, f_val %*% temp)

  return(projection)
}
